---
- name: Create mediawiki database 
  mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ VAR_MARIADB_PASSWORD }}"
    name: "{{ VAR_MEDIAWIKI_DB }}"
    state: present

- name: Create mediawiki user
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{ VAR_MARIADB_PASSWORD }}"
    name: "{{ VAR_MEDIAWIKI_DB_USER }}"
    password: "{{ VAR_MEDIAWIKI_DB_PASSWORD }}"
    priv: "{{ VAR_MEDIAWIKI_DB }}.*:ALL,GRANT"
    state: present
